# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9
clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
options:
  max-time: 10 # configure default 10 minute timeout
pipelines:
  custom:
    excelplusui:
    - step:
        name: build app
        caches:
          - node
          - sonar
        script: # Modify the commands below to build your repository.
          - npm uninstall -g @angular/cli
          - npm cache clean --force
          - npm install -g @angular/cli@1.7.4
          #- npm install -g sonarqube-scanner
          - npm install
          #- sonar-scanner -Dsonar.sources=src -Dsonar.tests=src -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
          - ls -ltr
          - ng build --prod --environment test -aot=false --sourcemaps --base-href .
          - mkdir -p revision && cp -r  dist revision/ &&  cp -r  scripts revision/ &&  cp   appspec.yml  revision/
          
          - ls
        artifacts:
          - revision/**
            
    - step:
        # set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION as environment variables
        name: Deploy to AWS
        deployment: production   # set to test, staging or production
        # trigger: manual  # uncomment to have a manual step
        image: atlassian/pipelines-awscli
        script:
          - echo Region ${AWS_DEFAULT_REGION}
          - echo Region ${AWS_ACCESS_KEY_ID}
          - echo Region ${AWS_SECRET_ACCESS_KEY}
          - ls -al
          - aws deploy push --application-name excel-plus-ui --s3-location s3://excel-plus/excel-plus/excel-plus-ui.zip --ignore-hidden-files --source ./revision
          - aws deploy create-deployment --application-name excel-plus-ui --s3-location bucket=excel-plus,key=excel-plus/excel-plus-ui.zip,bundleType=zip --deployment-group-name excel-plus-ui-group
          
            
